joint_limits:
  joint_1:
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    has_velocity_limits: true
    max_velocity: 3.054
    #has_acceleration_limits: true
    #max_acceleration: 5.0
    #has_jerk_limits: true
    #max_jerk: 100.0
    #has_effort_limits: true
    #max_effort: 1.0
  joint_2:
    has_position_limits: true
    min_position: -1.65806
    max_position: 2.70526
    has_velocity_limits: true
    max_velocity: 3.054
    #has_acceleration_limits: true
    #max_acceleration: 5.0
    #has_jerk_limits: true
    #max_jerk: 100.0
    #has_effort_limits: true
    #max_effort: 1.0
  joint_3:
    has_position_limits: true
    min_position: -3.14159
    max_position: 1.309
    has_velocity_limits: true
    max_velocity: 3.054
    #has_acceleration_limits: true
    #max_acceleration: 5.0
    #has_jerk_limits: true
    #max_jerk: 100.0
    #has_effort_limits: true
    #max_effort: 1.0
  joint_4:
    has_position_limits: true
    min_position: -6.981
    max_position: 6.981
    has_velocity_limits: true
    max_velocity: 6.283
    #has_acceleration_limits: true
    #max_acceleration: 5.0
    #has_jerk_limits: true
    #max_jerk: 100.0
    #has_effort_limits: true
    #max_effort: 1.0
  joint_5:
    has_position_limits: true
    min_position: -2.094
    max_position: 2.094
    has_velocity_limits: true
    max_velocity: 6.283
    #has_acceleration_limits: true
    #max_acceleration: 5.0
    #has_jerk_limits: true
    #max_jerk: 100.0
    #has_effort_limits: true
    #max_effort: 1.0
  joint_6:
    has_position_limits: true
    min_position: -6.98132
    max_position: 6.98132
    has_velocity_limits: true
    max_velocity: 6.28319
    #has_acceleration_limits: true
    #max_acceleration: 5.0
    #has_jerk_limits: true
    #max_jerk: 100.0
    #has_effort_limits: true
    #max_effort: 1.0
   